mongodb-js/nodejs-mongodb-legacy

etc/print_async_api.js
package-lock.json
package.json
test/tools/api.js
tsconfig.json

Uses api model library to simplify logic for finding async methods.
Constructs a file (`api.js`) that is intended to be curated by hand only after this PR which will be used to confirm coverage and construct table tests in mocha.

chore(NODE-4568): add api-extractor script

---

.gitignore
.mocharc.json
src/index.js
src/legacy_wrappers/admin.js
src/legacy_wrappers/bulk.js
src/legacy_wrappers/change_stream.js
src/legacy_wrappers/collection.js
src/legacy_wrappers/cursors.js
src/legacy_wrappers/db.js
src/legacy_wrappers/gridfs.js
src/legacy_wrappers/mongo_client.js
src/legacy_wrappers/session.js
src/utils.js
test/hooks/addons.js
test/tools/api.js
test/unit/index.test.js
test/unit/utils.test.js

Adds the legacy wrappers for our driver's async APIs.
Backwards compat.

feat(NODE-4541): implement legacy callback wrapper library

---

src/legacy_wrappers/mongo_client.js
src/utils.js
test/unit/legacy_wrappers/mongo_client.test.js

The MongoClient will set the driverInfo.name property to contain `mongodb-legacy`
To get insight into callback usage

feat(NODE-4559): add mongodb-legacy metadata

---

src/index.js

[NODE-4626](https://jira.mongodb.org/browse/NODE-4626)
Removing the old patch nested imports. The current version of the driver fails because we're missing exports, the latest passes because we changed the exports.

fix(NODE-4626): remove nested import logic

---

mongodb-legacy.d.ts

The insertOne method cannot be used in Typescript with callbacks because the callback typings are missing.
Adding the missing callback typings for the insertOne method in mongo-legacy.d.ts.
No
The possibility to use the insertOne method with callbacks.

fix(NODE-4957): Missing callback typings for insertOne method

---

src/legacy_wrappers/cursors.js
test/tools/api.js
test/unit/legacy_wrappers/collection.test.js
test/unit/legacy_wrappers/db.test.js

Fix cloned cursors not being transformed to legacy instances.

fix(NODE-5002): cloned cursors are not legacy api

---

src/legacy_wrappers/cursors.js
test/tools/api.js
test/unit/legacy_wrappers/collection.test.js
test/unit/legacy_wrappers/db.test.js

fix(NODE-5003): cloned cursors are not legacy api

---

package-lock.json
package.json
test/unit/legacy_wrappers/mongo_client.test.js
tsconfig.json

Update dependencies, fix tsconfig to declare the same lib settings as the driver
```
@microsoft/api-extractor-model    ^7.23.1  →  ^7.26.7
@typescript-eslint/eslint-plugin  ^5.33.0  →  ^5.59.2
@typescript-eslint/parser         ^5.33.0  →  ^5.59.2
chai                               ^4.3.6  →   ^4.3.7
eslint-config-prettier             ^8.5.0  →   ^8.8.0
mocha                             ^10.0.0  →  ^10.2.0
prettier                           ^2.7.1  →   ^2.8.8
sinon                             ^14.0.0  →  ^15.0.4
typescript                         ^4.7.4  →   ^5.0.4
```
notably did not upgrade:
```
mongodb                            ^5.0.0  →   ^5.3.0
```
The faas changes to client metadata moved the driver version property to the correct place, nested under `driver` so the unit tests …

chore(NODE-5258): update dependencies

---

.github/actions/setup/action.yml
.github/pull_request_template.md
.github/scripts/highlights.mjs
.github/scripts/pr_list.mjs
.github/scripts/release_notes.mjs
.github/scripts/util.mjs
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/release_notes.yml
package-lock.json
package.json

Adds release automation from driver
No
- Provenance release automation
- Release notes generation

chore(NODE-5387): add release automation

---

.github/workflows/release.yml

Adds id-token permission for releasing
None.
Needed for releases.

chore(NODE-5434): add id-token permission to release workflow

---

.github/workflows/release.yml

Move permissions, make release work again
No

chore(NODE-5476): move id-token permission to workflow

---

package-lock.json
package.json

Update the following dev dependencies
* "@microsoft/api-extractor-model": "^7.27.6"
* "sinon": "^15.2.0"
No
Bring dependencies up to date

chore(NODE-5520): update legacy dependencies

---

readme.md

NODE-5529
Added table with version compat info for the nodejs driver
This is documentation
Clarity about add-on compatibility
- [N/A] Ran `npm run check:lint` script
- [N/A] Changes are covered by tests
- [N/A] New TODOs have a related JIRA ticket

docs(NODE-5529): add driver compat table

---

package-lock.json
package.json

- Provide a callback version of driver v6
v6.0.0 of this package depends on driver version `^6.0.0`. It can be used to migrate existing callback using codebases to promises incrementally while pulling in the latest and greatest MongoDB has to offer!

feat(NODE-5585)!: adopt mongodb driver v6

---

.github/scripts/pr_list.mjs

- dedupe pr list
- fix regexp
N/a

chore: fix pr_list script

---

.github/workflows/release_notes.yml

A comment "run release_notes" from an admin will now trigger the release notes automation. The workflow dispatch also works.
Will update the release instructions document.
Commenting on the release PR is a more convenient UX than the workflow dispatch. This also removes the need to select the branch from that pane as we checkout the ref based on PR number.

chore(NODE-5769): add comment trigger for release notes

---

.github/actions/compress_sign_and_upload/action.yml
.github/workflows/release.yml
readme.md

Sign releases in legacy driver.
Automate release signing with a detached signature and verification instructions in the README.
[Link to an example of release signatures working with v2](https://github.com/mongodb/js-bson/actions/runs/9352138423/job/25739562707) (if you check the artifact link at the end of the compress_sign step, you can see the signature)
No
SSDLC Compliance
The Github release for `mongodb-legacy` now contains a detached signature file for the NPM package (named
`mongodb-legacy-X.Y.Z.tgz.sig`), on every major and patch release.  To verify the signature, follow the instructions in the 'Release Integrity' section of the `README.md` file.

feat(NODE-6158): add signature to github releases

---

readme.md

Updates the release integrity section with links to the GPG key and npm note.
readme.md
None
NODE-6238

docs(NODE-6238): update release integrity section

---

readme.md
src/legacy_wrappers/session.js
test/tools/api.js

- Add optional options pass through
- No public API changes
No
- The driver is adding an optional options object to these APIs we need to pass it through to enable it in our tests.
> [!NOTE]
> A correction has been made to an API that is only relevant to driver internals. There are no public-facing API changes in this fix.

fix(NODE-6328): pass through optional options in txn APIs

---

.eslintrc.json
src/legacy_wrappers/cursors.js
test/tools/api.js

fix(NODE-6420): support options for aggregationcursor/findcursor.explain()

---

release-please-config.json

chore(NODE-6970): remove skip-ci from release PR title
